In [1]:
1+1

2

In [2]:
2+2;

In [3]:
?println

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` followed by a newline. If `io` is not supplied, prints to [`stdout`](@ref).

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello, world")

julia> String(take!(io))
"Hello, world\n"
```


In [4]:
;ls


Untitled.ipynb


In [5]:
;pwd

/c/Users/Rahul/Desktop/julia


In [6]:
print("hello world",40)

hello world40

In [7]:
answer=42
typeof(answer)

Int64

In [8]:
x= "😃"

"😃"

In [9]:
typeof(x)

String

In [10]:
#=
hello this is comment
=#

In [11]:
10^2 #exponent  

100

In [12]:
a='hello' #thsi is an error

LoadError: syntax: invalid character literal

In [13]:
# string interpolation
# can use $ sign to insert existing variables into a string
name ="rahul"
println("my name is $name ")

my name is rahul 


In [14]:
x=10
y=10
print("the sum of digits is $(x+y)")

the sum of digits is 20

<h1>String concatenation

In [15]:
a="hello "
b="world"
string(a,b) # concatenation

"hello world"

In [16]:
print("this is ",a,"wrld")

this is hello wrld

In [17]:
a*b # also string concatetion

"hello world"

In [18]:
"hi" ^100 # use exponention for multiple string

"hihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi"

<h1> datastructures

<h3>Tuples

<h6>we can create tuples by using ( )

<h5> julia indexes start from 1

In [19]:
x=("hello","this","is","rahul")

("hello", "this", "is", "rahul")

In [20]:
x[3]  # acessing through index

"is"

In [21]:
# named tuples
y=(one="hello",two="world")

(one = "hello", two = "world")

In [22]:
y.one

"hello"

<h2> DICTIONARY

In [23]:
mine=Dict()

Dict{Any,Any} with 0 entries

In [24]:
book=Dict("1"=>"rahul","2"=>"raj")

Dict{String,String} with 2 entries:
  "1" => "rahul"
  "2" => "raj"

In [25]:
book["1"]

"rahul"

In [26]:
book["3"]="rakesh"

"rakesh"

In [27]:
book

Dict{String,String} with 3 entries:
  "1" => "rahul"
  "2" => "raj"
  "3" => "rakesh"

In [28]:
pop!(book,"3")  # pop! is used pop the element

"rakesh"

In [29]:
book


Dict{String,String} with 2 entries:
  "1" => "rahul"
  "2" => "raj"

<h4>ARRAYS

In [30]:
array=["hello","world","rahul"]   # 1 here is to signify its an 1D array

3-element Array{String,1}:
 "hello"
 "world"
 "rahul"

In [31]:
a2=[1,2,3,"rahul"] # mixed elements

4-element Array{Any,1}:
 1
 2
 3
  "rahul"

In [32]:
a2[1]

1

In [33]:
a2[4]

"rahul"

In [34]:
a2[4]="raj"

"raj"

In [35]:
a2

4-element Array{Any,1}:
 1
 2
 3
  "raj"

In [36]:
push!(a2,"rahul") # push element to the end of array

5-element Array{Any,1}:
 1
 2
 3
  "raj"
  "rahul"

In [37]:
twoD=[[1,2,3],[4,5,6]]

2-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5, 6]

In [38]:
str=[["rahul","raj"],["ketan","om"]]

2-element Array{Array{String,1},1}:
 ["rahul", "raj"]
 ["ketan", "om"]

In [39]:
rand(4,3) #2D array

4×3 Array{Float64,2}:
 0.327838  0.879078  0.451837
 0.432079  0.245243  0.779115
 0.756762  0.898463  0.579977
 0.643683  0.683893  0.922887

In [40]:
rand(1:10,4,3)

4×3 Array{Int64,2}:
 7   9  8
 1  10  8
 6   4  5
 4   9  3

In [41]:
rand(4,3,2)

4×3×2 Array{Float64,3}:
[:, :, 1] =
 0.245007   0.342435   0.893096
 0.0624738  0.0219023  0.437334
 0.968988   0.39566    0.360161
 0.0405458  0.141813   0.284774

[:, :, 2] =
 0.128968  0.626888  0.0662809
 0.783643  0.331349  0.343187
 0.569547  0.196144  0.200789
 0.78568   0.912077  0.71345

In [42]:
a3=copy(a2) # to create copy of array

5-element Array{Any,1}:
 1
 2
 3
  "raj"
  "rahul"

<h3> LOOPS :
    
       while
       for

while loops:

    while "condition"
           "loop body"
    end

In [43]:
n=0
while n<10
    n+=1
    println(n)
end
n

1
2
3
4
5
6
7
8
9
10


10

In [44]:
n=["rahul","raj","ketan"]
i=1

while i<=length(n)
    println(n[i])
    i+=1
end

rahul
raj
ketan


 <h3> FOR LOOPS
    
    for "var" in "loop iterable"
    "loop body"
    end

In [45]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [46]:
for i in 1:2:10
    println(i) 
end

1
3
5
7
9


In [47]:
m,n=5,5   # used to create 5X5 matrix with 0's
a=fill(0,(m,n))  

5×5 Array{Int64,2}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [48]:
for i in 1:m # populate the array
    for j in 1:n
        a[i,j]=i+j
    end
end
a

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [49]:
b=fill(0,(m,n))

5×5 Array{Int64,2}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [50]:
for i in 1:m,j in 1:n # same as above
    b[i,j]=i+j
end
b

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

<h4> LIST COMPREHENSION

In [51]:
[x^3 for x in 1:100]

100-element Array{Int64,1}:
       1
       8
      27
      64
     125
     216
     343
     512
     729
    1000
    1331
    1728
    2197
       ⋮
  704969
  729000
  753571
  778688
  804357
  830584
  857375
  884736
  912673
  941192
  970299
 1000000

In [52]:
c=[i+j for i in 1:m,j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

<h2> CONDITIONALS

  <h4> if keyword

In [56]:
n=83
if(n %3==0) && (n%5==0)  # '&&' ,'isequal' both are similar to 'AND'
    print("Fizzbuzz")
elseif n%3==0
    print("fizz")
elseif n%5==0
    print("buzz") 
else
    print(n)
end

83

<h3> TERNARY operator

a ? b : c

 which is equal to:
 
if a

    b
else

    c
end


In [60]:
x=300
y=200

200

In [61]:
if x>y  # normal if condition
    x
else
    y
end

300

The above code can be also written as:


In [62]:
(x > y) ? x : y  # ternary condition

300

<h4> short circuit evaluation
    <h6> we have already seen expression 
        a && b
        
to return true if both a and b are true. if a is false julia doesn't even need to know the value of b in order to determine that the overall result will be false. so julia doesn't even need to check what b is; it can be  just 'short-circuited' and immediately return false   

In [63]:
false && true

false

In [66]:
false && (println("hi");true) # here it doesn't even check secongd condition

false

In [69]:
(x<0) && error("x cannot be greater") # try x>0 will get a different result 

false

In [70]:
true || print("hi") # just evaluates 1st condition

true

<h2> FUNCTIONS

1.how to declare a function

2.duck typing in julia

3.mutating vs non-mutating

4.higher order functions

In [73]:
function hello(name) #function definitiom
    print("hello $name")
end
    

hello (generic function with 1 method)

In [75]:
hello("rahul") # function call

hello rahul

we can also declare fucntions in a single line

In [76]:
hello(name) =print("hello $name")

hello (generic function with 1 method)

In [77]:
hello("rahul")

hello rahul

declaring anonymous functions

In [80]:
hello1= name -> print("hello $name")

#11 (generic function with 1 method)

In [81]:
hello1("rahul")

hello rahul

In [82]:
f= x -> x^2

#13 (generic function with 1 method)

In [83]:
f(4)

16

In [90]:
div = (x,y) -> print(x/y) #division function

#21 (generic function with 1 method)

In [92]:
div(30,15)

2.0

<h4> duck-typing

 julia functions will work on whatever input makes sense

In [95]:
hello(123) # even if integer is passes as input 

hello 123

In [103]:
a=rand(3,3)

3×3 Array{Float64,2}:
 0.295938  0.801796  0.795606
 0.836358  0.764483  0.155144
 0.272973  0.813931  0.265211

In [104]:
f(a) # sqaures every number

3×3 Array{Float64,2}:
 0.975347  1.49781  0.570847
 0.929241  1.3813   0.825162
 0.833916  1.05697  0.413792